/* ========== 纸上良方 · 本地数据层 v2.1 ========== */
var BookPillData = (function(){
  var KEY = 'bookpill_submissions';
  var CONTRIBUTOR_PROFILE_KEY = 'bookpill_contributor_profile_v2';

  function _read(){
    try{
      var raw = localStorage.getItem(KEY);
      if(!raw) return [];
      var data = JSON.parse(raw);
      return Array.isArray(data) ? data : [];
    }catch(e){ return []; }
  }

  function _write(arr){
    try{
      localStorage.setItem(KEY, JSON.stringify(arr));
      return true;
    }catch(e){ return false; }
  }

  function _id(){
    return 'sub_' + Date.now().toString(36) + Math.random().toString(36).slice(2,6);
  }

  /* ========== CRUD ========== */

  function getAll(){
    return _read().sort(function(a,b){
      return new Date(b.createdAt) - new Date(a.createdAt);
    });
  }

  function getById(id){
    return _read().find(function(s){ return s.id === id; });
  }

  function add(submission){
    var arr = _read();
    var now = new Date().toISOString();
    var item = {
      id: submission.id || _id(),
      title: submission.title || '',
      author: submission.author || '',
      domain: submission.domain || '',
      scene: submission.scene || '',
      insight: submission.insight || '',
      bookDesc: submission.bookDesc || '',
      prescription: submission.prescription || '',
      quote: submission.quote || '',
      audience: submission.audience || '',
      contributor: submission.contributor || '',
      note: submission.note || '',
      tags: submission.tags || [],
      publisher: submission.publisher || '',
      pageCount: submission.pageCount || 0,
      publishedDate: submission.publishedDate || '',
      language: submission.language || '',
      isbn: submission.isbn || '',
      steps: submission.steps || [],
      keywordsMatched: submission.keywordsMatched || [],
      autoGenerated: submission.autoGenerated || {},
      status: submission.status || 'pending',
      createdAt: submission.createdAt || now,
      updatedAt: submission.updatedAt || now
    };
    arr.push(item);
    _write(arr);
    return item;
  }

  function update(id, fields){
    var arr = _read();
    var idx = arr.findIndex(function(s){ return s.id === id; });
    if(idx < 0) return null;
    for(var k in fields){
      if(fields.hasOwnProperty(k)) arr[idx][k] = fields[k];
    }
    arr[idx].updatedAt = new Date().toISOString();
    _write(arr);
    return arr[idx];
  }

  function setStatus(id, status){
    return update(id, { status: status });
  }

  function remove(id){
    var arr = _read();
    var filtered = arr.filter(function(s){ return s.id !== id; });
    _write(filtered);
    return arr.length !== filtered.length;
  }

  function clear(){
    return _write([]);
  }

  /* ========== Counts & Stats ========== */

  function count(){
    return _read().length;
  }

  function countByStatus(status){
    return _read().filter(function(s){ return s.status === status; }).length;
  }

  function countByDomain(domain){
    return _read().filter(function(s){ return s.domain === domain; }).length;
  }

  function getDomainBreakdown(){
    var arr = _read();
    var map = {};
    arr.forEach(function(s){
      var d = s.domain || '未分';
      if(!map[d]) map[d] = { domain: d, count: 0, pending: 0, accepted: 0, rejected: 0 };
      map[d].count++;
      var st = s.status || 'pending';
      map[d][st] = (map[d][st] || 0) + 1;
    });
    return Object.values(map).sort(function(a,b){ return b.count - a.count; });
  }

  function getMonthlyTrend(months){
    months = months || 6;
    var arr = _read();
    var buckets = [];
    var now = new Date();
    for(var i = months - 1; i >= 0; i--){
      var d = new Date(now.getFullYear(), now.getMonth() - i, 1);
      buckets.push({
        label: (d.getMonth() + 1) + '月',
        year: d.getFullYear(),
        m: d.getMonth(),
        count: 0
      });
    }
    arr.forEach(function(s){
      var d = new Date(s.createdAt);
      for(var i = 0; i < buckets.length; i++){
        if(d.getFullYear() === buckets[i].year && d.getMonth() === buckets[i].m){
          buckets[i].count++;
          break;
        }
      }
    });
    return buckets;
  }

  function getContributorRanking(limit){
    limit = limit || 10;
    var arr = _read();
    var map = {};
    arr.forEach(function(s){
      var name = s.contributor || '匿名';
      if(!map[name]){
        map[name] = {
          name: name,
          count: 0,
          accepted: 0,
          pending: 0,
          rejected: 0,
          domains: {},
          latest: s.createdAt,
          first: s.createdAt
        };
      }
      map[name].count++;
      var st = s.status || 'pending';
      map[name][st] = (map[name][st] || 0) + 1;
      if(s.domain){
        map[name].domains[s.domain] = (map[name].domains[s.domain] || 0) + 1;
      }
      if(new Date(s.createdAt) > new Date(map[name].latest)) map[name].latest = s.createdAt;
      if(new Date(s.createdAt) < new Date(map[name].first)) map[name].first = s.createdAt;
    });
    return Object.values(map).sort(function(a,b){
      if(b.accepted !== a.accepted) return b.accepted - a.accepted;
      return b.count - a.count;
    }).slice(0, limit);
  }

  function getContributors(){
    var arr = _read();
    var map = {};
    arr.forEach(function(s){
      var name = s.contributor || '匿名';
      if(!map[name]) map[name] = { name: name, count: 0, latest: s.createdAt };
      map[name].count++;
      if(new Date(s.createdAt) > new Date(map[name].latest)) map[name].latest = s.createdAt;
    });
    return Object.values(map).sort(function(a,b){ return b.count - a.count; });
  }

  function getTagCloud(){
    var arr = _read();
    var map = {};
    arr.forEach(function(s){
      var tags = s.tags || [];
      tags.forEach(function(t){
        if(!t) return;
        map[t] = (map[t] || 0) + 1;
      });
      if(s.domain) map['域·' + s.domain] = (map['域·' + s.domain] || 0) + 1;
    });
    return Object.entries(map)
      .map(function(e){ return { tag: e[0], count: e[1] }; })
      .sort(function(a,b){ return b.count - a.count; })
      .slice(0, 40);
  }

  function getSummaryStats(){
    var arr = _read();
    var total = arr.length;
    var pending = arr.filter(function(s){ return s.status === 'pending'; }).length;
    var accepted = arr.filter(function(s){ return s.status === 'accepted'; }).length;
    var rejected = arr.filter(function(s){ return s.status === 'rejected'; }).length;
    var uniqueContributors = {};
    arr.forEach(function(s){ uniqueContributors[s.contributor || '匿名'] = true; });
    var contribCount = Object.keys(uniqueContributors).length;
    var domains = getDomainBreakdown();
    var last7 = 0;
    var cutoff = Date.now() - 7 * 86400 * 1000;
    arr.forEach(function(s){ if(new Date(s.createdAt).getTime() >= cutoff) last7++; });
    var acceptRate = total > 0 ? Math.round((accepted / total) * 100) : 0;
    return {
      total: total,
      pending: pending,
      accepted: accepted,
      rejected: rejected,
      uniqueContributors: contribCount,
      domainCount: domains.length,
      last7: last7,
      acceptRate: acceptRate,
      byDomain: domains,
      monthly: getMonthlyTrend(6)
    };
  }

  /* ========== Contributor Profile (local memory) ========== */

  function getContributorProfile(){
    try{
      var raw = localStorage.getItem(CONTRIBUTOR_PROFILE_KEY);
      if(!raw) return null;
      return JSON.parse(raw);
    }catch(e){ return null; }
  }

  function setContributorProfile(profile){
    try{
      localStorage.setItem(CONTRIBUTOR_PROFILE_KEY, JSON.stringify(profile));
      return true;
    }catch(e){ return false; }
  }

  function clearContributorProfile(){
    try{
      localStorage.removeItem(CONTRIBUTOR_PROFILE_KEY);
      return true;
    }catch(e){ return false; }
  }

  /* ========== Export ========== */

  function exportJSON(){
    return JSON.stringify(_read(), null, 2);
  }

  function exportCSV(){
    var arr = _read();
    var headers = ['id','title','author','domain','scene','insight','bookDesc','prescription','quote','audience','contributor','note','tags','publisher','pageCount','publishedDate','language','isbn','status','createdAt','updatedAt'];
    var lines = [headers.join(',')];
    arr.forEach(function(s){
      var row = headers.map(function(h){
        var val;
        if(h === 'tags'){
          val = (s.tags || []).join('|');
        }else{
          val = (s[h] || '').toString();
        }
        if(val.indexOf(',') >= 0 || val.indexOf('"') >= 0 || val.indexOf('\n') >= 0){
          val = '"' + val.replace(/"/g, '""') + '"';
        }
        return val;
      });
      lines.push(row.join(','));
    });
    return lines.join('\n');
  }

  function exportMarkdownSummary(){
    var stats = getSummaryStats();
    var contr = getContributorRanking(5);
    var lines = [];
    lines.push('# 纸上良方 · 社区共建统计报告');
    lines.push('');
    lines.push('生成时间：' + new Date().toLocaleString('zh-CN'));
    lines.push('');
    lines.push('## 概览');
    lines.push('');
    lines.push('- **总投稿数**：' + stats.total);
    lines.push('- **已收录**：' + stats.accepted + '（收录率 ' + stats.acceptRate + '%）');
    lines.push('- **待审核**：' + stats.pending);
    lines.push('- **未通过**：' + stats.rejected);
    lines.push('- **投稿人数**：' + stats.uniqueContributors);
    lines.push('- **覆盖问题域**：' + stats.domainCount + ' 个');
    lines.push('- **近 7 天新增**：' + stats.last7);
    lines.push('');
    lines.push('## 各脉投稿分布');
    lines.push('');
    stats.byDomain.forEach(function(d){
      lines.push('- **' + d.domain + '**：' + d.count + '（收录 ' + d.accepted + ' / 待审 ' + d.pending + '）');
    });
    lines.push('');
    lines.push('## 贡献榜 Top 5');
    lines.push('');
    contr.forEach(function(c, i){
      lines.push((i+1) + '. **' + c.name + '**：累计投稿 ' + c.count + ' 本，收录 ' + c.accepted + ' 本');
    });
    return lines.join('\n');
  }

  return {
    getAll: getAll,
    getById: getById,
    add: add,
    update: update,
    setStatus: setStatus,
    remove: remove,
    clear: clear,
    count: count,
    countByStatus: countByStatus,
    countByDomain: countByDomain,
    getDomainBreakdown: getDomainBreakdown,
    getMonthlyTrend: getMonthlyTrend,
    getContributors: getContributors,
    getContributorRanking: getContributorRanking,
    getTagCloud: getTagCloud,
    getSummaryStats: getSummaryStats,
    getContributorProfile: getContributorProfile,
    setContributorProfile: setContributorProfile,
    clearContributorProfile: clearContributorProfile,
    exportJSON: exportJSON,
    exportCSV: exportCSV,
    exportMarkdownSummary: exportMarkdownSummary,
    KEY: KEY,
    CONTRIBUTOR_PROFILE_KEY: CONTRIBUTOR_PROFILE_KEY
  };


})();
/* ========== 本地图书数据库（热门中文书籍精选） ========== */
var LOCAL_BOOK_CATALOG = [
  {title:'房思琪的初恋乐园',author:'林奕含',publisher:'北京联合出版公司',publishedDate:'2018',pageCount:272,language:'zh',isbn:'9787559613431',categories:['文学','散文','女性','创伤'],desc:'《房思琪的初恋乐园》是作家林奕含的长篇小说，以极度真实和细腻的笔触，讲述了少女房思琪长期遭受补习班老师李国华诱奸和精神控制的痛苦经历。作者以亲身经历为基底，用文学的方式撕开了权力结构、性别压迫与家庭忽视的三重伤口，唤起了社会对儿童性侵害、权力不对等关系下的创伤议题的广泛关注，是当代华语文学中极具力量的女性发声之作。',domain:['创伤','内耗','表达','自我','治愈','关系','愤怒']},
  {title:'被讨厌的勇气',author:'岸见一郎 / 古贺史健',publisher:'机械工业出版社',publishedDate:'2015',pageCount:194,language:'zh',isbn:'9787111495160',categories:['心理学','自我成长','人际关系'],desc:'本书以对话形式展开，通过哲人和青年的五夜对话，系统阐述了阿德勒心理学的核心思想。阿德勒心理学认为，人的痛苦大多来自"课题混淆"——把别人的课题当成自己的课题。书中提出"一切烦恼皆源于人际关系"，并给出了"分离课题""被讨厌的勇气""甘于平凡"等实践性的观点，帮助读者摆脱他人的期待，活出真实的自己。',domain:['焦虑','内耗','人际关系','自我']},
  {title:'活着',author:'余华',publisher:'作家出版社',publishedDate:'2012',pageCount:240,language:'zh',isbn:'9787506365437',categories:['文学','小说','人生'],desc:'《活着》讲述了农村人福贵悲惨的人生遭遇。福贵本是个阔少爷，可他嗜赌如命，终于赌光了家业一贫如洗。他的父亲被他活活气死，母亲则在穷困中患了重病。福贵为了给母亲治病，走上了卖血的路。',domain:['内耗','自我','成长','治愈','焦虑']},
  {title:'百年孤独',author:'加西亚·马尔克斯',publisher:'南海出版公司',publishedDate:'2011',pageCount:360,language:'zh',isbn:'9787544253994',categories:['文学','小说','魔幻现实主义'],desc:'《百年孤独》是哥伦比亚作家加西亚·马尔克斯的代表作，也是拉丁美洲魔幻现实主义文学的代表作。小说描写了布恩迪亚家族七代人的传奇故事，以及加勒比海沿岸小镇马孔多的百年兴衰，反映了拉丁美洲一个世纪以来风云变幻的历史。',domain:['成长','思维','内耗','自我','治愈']},
  {title:'悲惨世界',author:'维克多·雨果',publisher:'人民文学出版社',publishedDate:'2015',pageCount:1588,language:'zh',isbn:'9787020104376',categories:['文学','小说','法国文学','人道主义'],desc:'《悲惨世界》是法国文豪维克多·雨果的代表作，以19世纪法国社会为背景，通过苦役犯冉·阿让被主教米里哀宽恕后洗心革面、一生践行人道与救赎的宏大故事，交织了芳汀、珂赛特、马吕斯、沙威等人物在贫困、压迫、法律、革命与爱中的挣扎与抉择。作品气势恢宏、悲天悯人，深刻探讨了正义、慈悲、救赎与人性之善，被誉为"人道主义的史诗"。',domain:['内耗','治愈','成长','自我','情商','关系','焦虑']},
  {title:'三体',author:'刘慈欣',publisher:'重庆出版社',publishedDate:'2008',pageCount:302,language:'zh',isbn:'9787536692930',categories:['科幻','小说','文学'],desc:'文化大革命如火如荼进行的同时，军方探寻外星文明的绝秘计划"红岸工程"取得了突破性进展。但是在按下发射键的那一刻，历经劫难的叶文洁没有意识到，她彻底改变了人类的命运。四十年后，历史在苍茫中再度浮现，而人类文明也已经走到了最危险的时刻。',domain:['思维','焦虑']},
  {title:'原子习惯',author:'詹姆斯·克利尔',publisher:'北京联合出版公司',publishedDate:'2019',pageCount:320,language:'zh',isbn:'9787559634999',categories:['自我成长','习惯','心理学'],desc:'本书提出了一个简单但强大的框架——用 1% 的微小改变，创造复利式的惊人成果。作者詹姆斯·克利尔是习惯养成领域的权威专家，他总结了行为设计的四大定律：让它显而易见、让它有吸引力、让它简便易行、让它令人愉悦。',domain:['拖延','自律','习惯','效率','行动']},
  {title:'掌控习惯',author:'詹姆斯·克利尔',publisher:'北京联合出版公司',publishedDate:'2019',pageCount:320,language:'zh',isbn:'9787559634999',categories:['自我成长','习惯','心理学'],desc:'（同《原子习惯》）本书提出用微小的习惯改变，创造复利式的人生成果。',domain:['拖延','自律','习惯','效率']},
  {title:'思考，快与慢',author:'丹尼尔·卡尼曼',publisher:'中信出版社',publishedDate:'2012',pageCount:440,language:'zh',isbn:'9787508633558',categories:['心理学','思维','决策'],desc:'在书中，卡尼曼介绍了很多经典有趣的行为实验，指出我们在什么情况下可以相信自己的直觉，什么时候不能相信；指导我们如何在商场、职场和个人生活中作出更好的选择。',domain:['思维','决策','认知']},
  {title:'原则',author:'瑞·达利欧',publisher:'中信出版社',publishedDate:'2018',pageCount:576,language:'zh',isbn:'9787508684030',categories:['商业','管理','思维'],desc:'《原则》一书分享了桥水基金创始人瑞·达利欧的生活和工作原则，分为生活原则和工作原则两部分。',domain:['思维','决策','自律','成长']},
  {title:'深度工作',author:'卡尔·纽波特',publisher:'江西人民出版社',publishedDate:'2017',pageCount:288,language:'zh',isbn:'9787210092683',categories:['自我成长','效率','工作'],desc:'在这个信息爆炸的时代，如何专注？本书作者、美国乔治城大学计算机科学副教授卡尔·纽波特为我们提供了一套实现深度工作的方法和准则。',domain:['专注','效率','工作']},
  {title:'乌合之众',author:'古斯塔夫·勒庞',publisher:'中央编译出版社',publishedDate:'2011',pageCount:220,language:'zh',isbn:'9787511714592',categories:['心理学','社会','群体'],desc:'《乌合之众》是法国社会心理学家古斯塔夫·勒庞的经典著作，被誉为"群体心理学的奠基之作"。书中剖析了大众心理的种种特征。',domain:['表达','人际关系','思维']},
  {title:'影响力',author:'罗伯特·西奥迪尼',publisher:'辽宁教育出版社',publishedDate:'2006',pageCount:384,language:'zh',isbn:'9787538278707',categories:['心理学','商业','营销'],desc:'在这本书中，西奥迪尼博士为我们解释了为什么有些人极具说服力，而我们总是容易上当受骗。',domain:['表达','人际关系','情商']},
  {title:'非暴力沟通',author:'马歇尔·卢森堡',publisher:'华夏出版社',publishedDate:'2009',pageCount:220,language:'zh',isbn:'9787508051848',categories:['心理学','沟通','人际关系'],desc:'作为一个遵纪守法的好人，也许我们从来没有想过和"暴力"扯上关系。不过在日常生活中，我们在表达时常常会使用一些隐蔽的暴力。',domain:['表达','人际关系','情商','沟通']},
  {title:'关键对话',author:'帕特里克·格里森',publisher:'机械工业出版社',publishedDate:'2012',pageCount:280,language:'zh',isbn:'9787111378425',categories:['心理学','沟通','人际关系'],desc:'《关键对话》将帮助你应对沟通中最棘手的情况——当谈话双方情绪激烈、观点对立、后果严重时，如何进行有效的沟通。',domain:['表达','人际关系','情商','沟通']},
  {title:'蛤蟆先生去看心理医生',author:'罗伯特·戴博德',publisher:'天津人民出版社',publishedDate:'2020',pageCount:208,language:'zh',isbn:'9787201161693',categories:['心理学','心理咨询','自我成长'],desc:'《蛤蟆先生去看心理医生》是一本写给普通人的心理学入门读物。作者罗伯特·戴博德以童话的形式，讲述了蛤蟆先生在心理咨询师苍鹭的帮助下，探索自己内心世界的过程。',domain:['焦虑','抑郁','自我','成长','治愈']},
  {title:'也许你该找个人聊聊',author:'洛莉·戈特利布',publisher:'上海人民出版社',publishedDate:'2021',pageCount:308,language:'zh',isbn:'9787208168017',categories:['心理学','心理咨询','自我成长'],desc:'洛莉·戈特利布是一位心理治疗师，她在这本书中分享了自己与来访者的故事，以及她自己作为来访者的经历。',domain:['焦虑','抑郁','自我','成长','治愈','人际关系']},
  {title:'自卑与超越',author:'阿尔弗雷德·阿德勒',publisher:'上海三联书店',publishedDate:'2016',pageCount:256,language:'zh',isbn:'9787542655203',categories:['心理学','自我成长','个体心理学'],desc:'《自卑与超越》是阿德勒的代表作。阿德勒认为，自卑感是人类成长的动力，关键在于如何超越它。',domain:['自卑','成长','自我','人际关系']},
  {title:'心流',author:'米哈里·契克森米哈赖',publisher:'中信出版社',publishedDate:'2009',pageCount:264,language:'zh',isbn:'9787508614146',categories:['心理学','专注','效率'],desc:'本书作者米哈里·契克森米哈赖是积极心理学的奠基人之一。他发现，当人们全身心投入某项活动时，会进入一种"心流"状态。',domain:['专注','效率','自我','幸福']},
  {title:'刻意练习',author:'安德斯·艾利克森',publisher:'北京联合出版公司',publishedDate:'2016',pageCount:288,language:'zh',isbn:'9787550276417',categories:['自我成长','学习','效率'],desc:'安德斯·艾利克森博士的研究表明，卓越不是一种天赋，而是一种可以培养的习惯。通过正确的练习方法，任何人都可以在任何领域取得卓越成就。',domain:['自律','效率','学习','成长']},
  {title:'当下的力量',author:'埃克哈特·托利',publisher:'中信出版社',publishedDate:'2009',pageCount:248,language:'zh',isbn:'9787508614153',categories:['心理学','心灵','正念'],desc:'《当下的力量》是一本关于正念和临在的书。作者埃克哈特·托利引导我们关注当下这个时刻。',domain:['焦虑','抑郁','内耗','自我','治愈']},
  {title:'正念的奇迹',author:'一行禅师',publisher:'中央编译出版社',publishedDate:'2011',pageCount:200,language:'zh',isbn:'9787511708843',categories:['心理学','心灵','正念','禅修'],desc:'一行禅师是当今世界最具影响力的禅修大师之一。在这本书中，他用朴实无华的文字，教导我们如何在日常生活中修习正念。',domain:['焦虑','内耗','自我','治愈','专注']},
  {title:'焦虑的意义',author:'罗洛·梅',publisher:'广西师范大学出版社',publishedDate:'2010',pageCount:240,language:'zh',isbn:'9787563390041',categories:['心理学','焦虑','哲学'],desc:'罗洛·梅是美国存在主义心理学的开创者。在这本书中，他探讨了焦虑的本质，认为焦虑是人类存在的基本条件之一。',domain:['焦虑','内耗','自我','成长']},
  {title:'走出抑郁',author:'理查德·奥康纳',publisher:'中国纺织出版社',publishedDate:'2019',pageCount:224,language:'zh',isbn:'9787518063594',categories:['心理学','抑郁','心理咨询'],desc:'本书作者理查德·奥康纳是美国著名的心理治疗师。他在书中分享了抑郁症的成因、表现和治疗方法。',domain:['抑郁','焦虑','内耗','治愈','自我']},
  {title:'把时间当作朋友',author:'李笑来',publisher:'电子工业出版社',publishedDate:'2013',pageCount:272,language:'zh',isbn:'9787121213926',categories:['自我成长','时间管理','习惯'],desc:'《把时间当作朋友》是一本关于时间管理和自我成长的书。作者李笑来认为，时间管理的本质是自我管理。',domain:['拖延','时间管理','自律','习惯','效率']},
  {title:'时间简史',author:'史蒂芬·霍金',publisher:'湖南科学技术出版社',publishedDate:'2010',pageCount:216,language:'zh',isbn:'9787535732309',categories:['科普','物理','宇宙'],desc:'《时间简史》是史蒂芬·霍金的科普名著，介绍了宇宙的起源、时间的本质、黑洞等物理学前沿问题。',domain:['思维','认知']},
  {title:'万历十五年',author:'黄仁宇',publisher:'中华书局',publishedDate:'2006',pageCount:286,language:'zh',isbn:'9787101054355',categories:['历史','文学','明朝'],desc:'《万历十五年》是一部从技术角度看历史的经典著作。作者黄仁宇以1587年为切入点，分析了明朝衰败的深层原因。',domain:['思维','认知','成长']},
  {title:'人类简史',author:'尤瓦尔·赫拉利',publisher:'中信出版社',publishedDate:'2014',pageCount:440,language:'zh',isbn:'9787508644653',categories:['历史','人类学','科普'],desc:'《人类简史》从认知革命、农业革命到科学革命，讲述了人类从石器时代到21世纪的演化历程。',domain:['思维','认知','成长']},
  {title:'未来简史',author:'尤瓦尔·赫拉利',publisher:'中信出版社',publishedDate:'2017',pageCount:420,language:'zh',isbn:'9787508681435',categories:['历史','未来学','科普'],desc:'《未来简史》是《人类简史》的姊妹篇，探讨了智人未来的发展方向，包括人工智能、生物科技等前沿话题。',domain:['思维','认知']},
  {title:'今日简史',author:'尤瓦尔·赫拉利',publisher:'中信出版社',publishedDate:'2019',pageCount:320,language:'zh',isbn:'9787521718238',categories:['历史','社会','时事'],desc:'《今日简史》聚焦当下，分析了当今世界面临的十大挑战，包括恐怖主义、气候变化、人工智能等。',domain:['思维','认知','成长']},
  {title:'社会心理学',author:'戴维·迈尔斯',publisher:'人民邮电出版社',publishedDate:'2016',pageCount:588,language:'zh',isbn:'9787115410647',categories:['心理学','社会','人际关系'],desc:'《社会心理学》是一本系统介绍社会心理学基本理论和研究成果的教科书。',domain:['人际关系','思维','表达','情商']},
  {title:'亲密关系',author:'罗兰·米勒',publisher:'人民邮电出版社',publishedDate:'2015',pageCount:568,language:'zh',isbn:'9787115380841',categories:['心理学','人际关系','亲密关系'],desc:'《亲密关系》是一本探讨亲密关系的科学著作。作者罗兰·米勒从社会心理学的角度，分析了亲密关系的形成、发展和维持。',domain:['人际关系','情商','沟通','表达']},
  {title:'人性的弱点',author:'戴尔·卡耐基',publisher:'天津人民出版社',publishedDate:'2016',pageCount:328,language:'zh',isbn:'9787201108007',categories:['心理学','人际关系','自我成长'],desc:'《人性的弱点》是戴尔·卡耐基的经典之作。书中讲述了如何赢得朋友、如何影响他人、如何避免争论等实用的人际交往技巧。',domain:['人际关系','情商','表达','沟通']},
  {title:'纳瓦尔宝典',author:'埃里克·乔根森',publisher:'中信出版社',publishedDate:'2022',pageCount:280,language:'zh',isbn:'9787521744109',categories:['商业','思维','自我成长'],desc:'本书收录了天使投资人、作家纳瓦尔·拉维坎特的智慧箴言，涵盖了财富、幸福、人生哲学等多个主题。',domain:['思维','成长','自我','自律']},
  {title:'穷查理宝典',author:'彼得·考夫曼',publisher:'上海人民出版社',publishedDate:'2016',pageCount:560,language:'zh',isbn:'9787208134272',categories:['商业','投资','思维'],desc:'本书是查理·芒格的智慧箴言集，涵盖了他的人生哲学、投资理念、思维方式和处世智慧。',domain:['思维','决策','成长','自律']},
  {title:'穷爸爸富爸爸',author:'罗伯特·清崎',publisher:'中信出版社',publishedDate:'2000',pageCount:250,language:'zh',isbn:'9787508624481',categories:['商业','投资','理财'],desc:'《穷爸爸富爸爸》是一本关于财商教育的经典著作。作者罗伯特·清崎通过两个爸爸的故事，讲述了财富观念的重要性。',domain:['思维','成长','自律']},
  {title:'霍乱时期的爱情',author:'加西亚·马尔克斯',publisher:'南海出版公司',publishedDate:'2015',pageCount:402,language:'zh',isbn:'9787544270182',categories:['文学','小说','爱情'],desc:'《霍乱时期的爱情》是马尔克斯的另一部代表作，讲述了一段跨越半个世纪的爱情故事。',domain:['人际关系','成长','自我']},
  {title:'没有人给他写信的上校',author:'加西亚·马尔克斯',publisher:'南海出版公司',publishedDate:'2015',pageCount:168,language:'zh',isbn:'9787544270199',categories:['文学','小说','拉美文学'],desc:'本书是马尔克斯的早期作品，讲述了一个退伍上校等待养老金的故事。',domain:['拖延','焦虑','自我']},
  {title:'2001太空漫游',author:'阿瑟·克拉克',publisher:'上海人民出版社',publishedDate:'2013',pageCount:250,language:'zh',isbn:'9787208119725',categories:['科幻','小说','太空'],desc:'《2001太空漫游》是阿瑟·克拉克的代表作，也是科幻文学的经典之作。',domain:['思维','认知']},
  {title:'三体II：黑暗森林',author:'刘慈欣',publisher:'重庆出版社',publishedDate:'2008',pageCount:302,language:'zh',isbn:'9787536693298',categories:['科幻','小说'],desc:'本书是《三体》系列的第二部，展开了人类文明与三体文明之间的宏大叙事。',domain:['思维','焦虑']},
  {title:'三体III：死神永生',author:'刘慈欣',publisher:'重庆出版社',publishedDate:'2010',pageCount:513,language:'zh',isbn:'9787536693328',categories:['科幻','小说'],desc:'本书是《三体》系列的第三部，也是完结篇，展示了宇宙的宏大与人类文明的渺小。',domain:['思维','认知']},
  {title:'球状闪电',author:'刘慈欣',publisher:'重庆出版社',publishedDate:'2005',pageCount:258,language:'zh',isbn:'9787536667007',categories:['科幻','小说'],desc:'《球状闪电》是刘慈欣的代表作之一，以球状闪电为核心展开了一个宏大的科幻叙事。',domain:['思维','认知']},
  {title:'流浪者',author:'刘慈欣',publisher:'科学普及出版社',publishedDate:'2003',pageCount:196,language:'zh',isbn:'9787110030608',categories:['科幻','小说'],desc:'（补充收录）刘慈欣的短篇科幻小说集。',domain:['思维','认知']},
  {title:'沙丘',author:'弗兰克·赫伯特',publisher:'江苏凤凰文艺出版社',publishedDate:'2017',pageCount:680,language:'zh',isbn:'9787559402270',categories:['科幻','小说','太空'],desc:'《沙丘》是弗兰克·赫伯特的代表作，也是科幻文学的经典之作。',domain:['思维','认知']},
  {title:'基地',author:'艾萨克·阿西莫夫',publisher:'江苏凤凰文艺出版社',publishedDate:'2015',pageCount:260,language:'zh',isbn:'9787539960601',categories:['科幻','小说','太空'],desc:'《基地》是阿西莫夫的基地系列的第一部，也是科幻文学的经典之作。',domain:['思维','认知']},
  {title:'乡土中国',author:'费孝通',publisher:'中华书局',publishedDate:'2013',pageCount:148,language:'zh',isbn:'9787101059756',categories:['社会学','人类学','中国'],desc:'《乡土中国》是费孝通的代表作，也是中国社会学的经典之作。书中分析了中国传统社会的结构和文化特征。',domain:['思维','认知','人际关系']},
  {title:'菊与刀',author:'鲁思·本尼迪克特',publisher:'商务印书馆',publishedDate:'1990',pageCount:246,language:'zh',isbn:'9787100022344',categories:['人类学','日本','文化'],desc:'《菊与刀》是美国人类学家鲁思·本尼迪克特的代表作，也是研究日本民族性的经典著作。',domain:['思维','认知','人际关系']},
  {title:'瓦尔登湖',author:'亨利·戴维·梭罗',publisher:'上海译文出版社',publishedDate:'2006',pageCount:320,language:'zh',isbn:'9787532741072',categories:['文学','散文','哲学'],desc:'《瓦尔登湖》是梭罗的散文集，记录了他在瓦尔登湖畔独居两年的生活和思考。',domain:['自我','成长','治愈','专注','内耗']},
  {title:'西西弗神话',author:'阿尔贝·加缪',publisher:'生活·读书·新知三联书店',publishedDate:'2012',pageCount:220,language:'zh',isbn:'9787108041238',categories:['哲学','文学','存在主义'],desc:'《西西弗神话》是加缪的哲学随笔集，集中阐述了他的荒诞哲学。',domain:['思维','焦虑','自我','成长']},
  {title:'鼠疫',author:'阿尔贝·加缪',publisher:'上海译文出版社',publishedDate:'2013',pageCount:360,language:'zh',isbn:'9787532761186',categories:['文学','小说','存在主义'],desc:'《鼠疫》是加缪的代表作之一，以瘟疫为隐喻，探讨了人类在荒诞境遇中的选择和抗争。',domain:['思维','自我','成长']},
  {title:'局外人',author:'阿尔贝·加缪',publisher:'上海译文出版社',publishedDate:'2013',pageCount:160,language:'zh',isbn:'9787532759144',categories:['文学','小说','存在主义'],desc:'《局外人》是加缪的成名作，讲述了一个对世界漠不关心的小职员默尔索的故事。',domain:['焦虑','自我','思维']},
  {title:'变形记',author:'弗兰茨·卡夫卡',publisher:'上海译文出版社',publishedDate:'2012',pageCount:260,language:'zh',isbn:'9787532757850',categories:['文学','小说','现代主义'],desc:'《变形记》是卡夫卡的代表作之一，讲述了一个推销员一觉醒来变成大甲虫的荒诞故事。',domain:['焦虑','自我','思维']},
  {title:'查拉图斯特拉如是说',author:'弗里德里希·尼采',publisher:'中华书局',publishedDate:'2009',pageCount:344,language:'zh',isbn:'9787101037426',categories:['哲学','文学','尼采'],desc:'《查拉图斯特拉如是说》是尼采的代表作，以诗一般的语言阐述了他的超人哲学。',domain:['思维','自我','成长']},
  {title:'人生的智慧',author:'阿图尔·叔本华',publisher:'上海人民出版社',publishedDate:'2014',pageCount:320,language:'zh',isbn:'9787208122811',categories:['哲学','人生','叔本华'],desc:'本书是叔本华的代表作之一，探讨了人生的意义、幸福的本质等哲学命题。',domain:['思维','焦虑','自我','成长']},
  {title:'自卑与超越',author:'阿尔弗雷德·阿德勒',publisher:'上海三联书店',publishedDate:'2016',pageCount:256,language:'zh',isbn:'9787542655203',categories:['心理学','自我成长','个体心理学'],desc:'《自卑与超越》是阿德勒的代表作。阿德勒认为，自卑感是人类成长的动力，关键在于如何超越它。',domain:['自卑','成长','自我','人际关系']},
  {title:'蛤蟆先生去看心理医生',author:'罗伯特·戴博德',publisher:'天津人民出版社',publishedDate:'2020',pageCount:208,language:'zh',isbn:'9787201161693',categories:['心理学','心理咨询','自我成长'],desc:'《蛤蟆先生去看心理医生》是一本写给普通人的心理学入门读物。',domain:['焦虑','抑郁','自我','成长','治愈']},
  {title:'也许你该找个人聊聊',author:'洛莉·戈特利布',publisher:'上海人民出版社',publishedDate:'2021',pageCount:308,language:'zh',isbn:'9787208168017',categories:['心理学','心理咨询','自我成长'],desc:'洛莉·戈特利布分享了自己与来访者的故事，以及她自己作为来访者的经历。',domain:['焦虑','抑郁','自我','成长','治愈','人际关系']},
  {title:'被讨厌的勇气',author:'岸见一郎 / 古贺史健',publisher:'机械工业出版社',publishedDate:'2015',pageCount:194,language:'zh',isbn:'9787111495160',categories:['心理学','自我成长','人际关系'],desc:'本书以对话形式展开，阐述了阿德勒心理学的核心思想。',domain:['焦虑','内耗','人际关系','自我']},
  {title:'第二性',author:'西蒙娜·德·波伏瓦',publisher:'上海译文出版社',publishedDate:'2011',pageCount:820,language:'zh',isbn:'9787532752985',categories:['哲学','女性主义','社会学'],desc:'《第二性》是波伏瓦的代表作，也是女性主义的经典之作。',domain:['思维','成长','自我','人际关系']},
  {title:'性政治',author:'凯特·米利特',publisher:'江苏人民出版社',publishedDate:'2000',pageCount:420,language:'zh',isbn:'9787214015327',categories:['社会学','女性主义','政治学'],desc:'《性政治》是女性主义文学批评的经典之作。',domain:['思维','人际关系','成长']},
  {title:'苏菲的世界',author:'乔斯坦·贾德',publisher:'作家出版社',publishedDate:'2007',pageCount:520,language:'zh',isbn:'9787506336826',categories:['哲学','小说','思想史'],desc:'《苏菲的世界》是一部关于哲学史的长篇小说，以少女苏菲收到的神秘信件为线索。',domain:['思维','认知','成长']},
  {title:'西决',author:'笛安',publisher:'长江文艺出版社',publishedDate:'2009',pageCount:216,language:'zh',isbn:'9787535441161',categories:['文学','小说','青春'],desc:'《西决》是笛安的长篇小说，讲述了一个家族的故事。',domain:['人际关系','成长','自我']},
  {title:'东霓',author:'笛安',publisher:'长江文艺出版社',publishedDate:'2010',pageCount:228,language:'zh',isbn:'9787535445695',categories:['文学','小说'],desc:'《东霓》是笛安《龙城三部曲》的第二部。',domain:['人际关系','自我','成长']},
  {title:'南音',author:'笛安',publisher:'长江文艺出版社',publishedDate:'2012',pageCount:280,language:'zh',isbn:'9787535451825',categories:['文学','小说'],desc:'《南音》是笛安《龙城三部曲》的完结篇。',domain:['人际关系','自我','成长']},
  {title:'他者的消失',author:'韩炳哲',publisher:'中信出版社',publishedDate:'2019',pageCount:120,language:'zh',isbn:'9787521710764',categories:['哲学','社会','文化'],desc:'韩炳哲探讨了当代社会中他者的消失和自我的异化。',domain:['焦虑','内耗','自我','思维']},
  {title:'倦怠社会',author:'韩炳哲',publisher:'中信出版社',publishedDate:'2019',pageCount:110,language:'zh',isbn:'9787521710771',categories:['哲学','社会','心理学'],desc:'韩炳哲分析了当代社会的倦怠现象，提出了"功绩社会"的概念。',domain:['焦虑','倦怠','自我','工作','效率']},
  {title:'爱欲之死',author:'韩炳哲',publisher:'中信出版社',publishedDate:'2020',pageCount:120,language:'zh',isbn:'9787521719599',categories:['哲学','心理学','文化'],desc:'韩炳哲探讨了当代社会中爱欲的消失和情感的贫乏。',domain:['焦虑','自我','人际关系']},
  {title:'在绝望之巅',author:'E.M.齐奥朗',publisher:'北京十月文艺出版社',publishedDate:'2020',pageCount:240,language:'zh',isbn:'9787530220926',categories:['哲学','文学','存在主义'],desc:'齐奥朗的哲学随笔集，探讨了绝望、虚无、存在等主题。',domain:['焦虑','抑郁','自我','成长','治愈']},
  {title:'自我',author:'克里斯托弗·吉莫',publisher:'机械工业出版社',publishedDate:'2018',pageCount:272,language:'zh',isbn:'9787111587325',categories:['心理学','自我成长','慈悲'],desc:'本书介绍了"自我慈悲"的概念，帮助读者以更温柔的方式对待自己。',domain:['自卑','焦虑','自我','治愈','成长']},
  {title:'为什么我们会睡不好',author:'马修·沃克',publisher:'中信出版社',publishedDate:'2017',pageCount:320,language:'zh',isbn:'9787508678169',categories:['科普','医学','睡眠'],desc:'本书作者马修·沃克是睡眠科学领域的权威专家，揭示了睡眠对人类健康的重要性。',domain:['健康','自律','效率','自我']},
  {title:'非对称风险',author:'纳西姆·塔勒布',publisher:'中信出版社',publishedDate:'2019',pageCount:380,language:'zh',isbn:'9787521709172',categories:['商业','金融','风险'],desc:'塔勒布在本书中探讨了风险和不确定性的本质，提出了"反脆弱"的概念。',domain:['思维','决策','自律']},
  {title:'反脆弱',author:'纳西姆·塔勒布',publisher:'中信出版社',publishedDate:'2014',pageCount:420,language:'zh',isbn:'9787508644882',categories:['商业','金融','哲学'],desc:'《反脆弱》是塔勒布的代表作之一，阐述了在不确定性中获益的哲学。',domain:['思维','决策','成长','自律']},
  {title:'黑天鹅',author:'纳西姆·塔勒布',publisher:'中信出版社',publishedDate:'2008',pageCount:360,language:'zh',isbn:'9787508611740',categories:['商业','金融','风险'],desc:'《黑天鹅》是塔勒布的成名作，探讨了极端不确定性事件的影响。',domain:['思维','决策','认知']},
  {title:'极度邪恶意象',author:'米兰·昆德拉',publisher:'上海译文出版社',publishedDate:'2014',pageCount:340,language:'zh',isbn:'9787532766203',categories:['文学','小说','存在主义'],desc:'本书是昆德拉的长篇小说，讲述了一个关于记忆和遗忘的故事。',domain:['思维','自我','人际关系']},
  {title:'不能承受的生命之轻',author:'米兰·昆德拉',publisher:'上海译文出版社',publishedDate:'2014',pageCount:360,language:'zh',isbn:'9787532765848',categories:['文学','小说','存在主义'],desc:'《不能承受的生命之轻》是昆德拉的代表作，探讨了生命中的轻与重。',domain:['思维','自我','成长','人际关系']},
  {title:'笑忘书',author:'米兰·昆德拉',publisher:'上海译文出版社',publishedDate:'2014',pageCount:320,language:'zh',isbn:'9787532765855',categories:['文学','小说'],desc:'《笑忘书》是昆德拉的长篇小说，讲述了记忆和遗忘的故事。',domain:['思维','自我','人际关系']},
  {title:'生活在别处',author:'米兰·昆德拉',publisher:'上海译文出版社',publishedDate:'2014',pageCount:280,language:'zh',isbn:'9787532765862',categories:['文学','小说'],desc:'《生活在别处》是昆德拉的早期作品。',domain:['思维','自我','成长']},
  {title:'道德情操论',author:'亚当·斯密',publisher:'商务印书馆',publishedDate:'2015',pageCount:420,language:'zh',isbn:'9787100115801',categories:['哲学','经济学','伦理学'],desc:'《道德情操论》是亚当·斯密的代表作之一，探讨了道德、情感和社会秩序。',domain:['思维','决策','人际关系']},
  {title:'国富论',author:'亚当·斯密',publisher:'商务印书馆',publishedDate:'2014',pageCount:960,language:'zh',isbn:'9787100115818',categories:['经济学','哲学','社会'],desc:'《国富论》是亚当·斯密的代表作，也是现代经济学的奠基之作。',domain:['思维','认知','决策']},
  {title:'资本论',author:'卡尔·马克思',publisher:'人民出版社',publishedDate:'2004',pageCount:1200,language:'zh',isbn:'9787010041159',categories:['经济学','哲学','政治'],desc:'《资本论》是马克思的代表作，也是马克思主义政治经济学的经典著作。',domain:['思维','认知','决策']},
  {title:'论法的精神',author:'孟德斯鸠',publisher:'商务印书馆',publishedDate:'2012',pageCount:820,language:'zh',isbn:'9787100088015',categories:['法学','哲学','社会'],desc:'《论法的精神》是孟德斯鸠的代表作，也是启蒙思想的经典之作。',domain:['思维','认知','决策']},
  {title:'社会契约论',author:'让-雅克·卢梭',publisher:'商务印书馆',publishedDate:'2011',pageCount:180,language:'zh',isbn:'9787100047195',categories:['哲学','政治','社会'],desc:'《社会契约论》是卢梭的代表作，也是现代政治哲学的奠基之作。',domain:['思维','认知','决策']},
  {title:'忏悔录',author:'让-雅克·卢梭',publisher:'商务印书馆',publishedDate:'2010',pageCount:680,language:'zh',isbn:'9787100034569',categories:['文学','哲学','自传'],desc:'《忏悔录》是卢梭的自传体作品，也是文学史上的经典之作。',domain:['自我','成长','思维']},
  {title:'爱弥儿',author:'让-雅克·卢梭',publisher:'商务印书馆',publishedDate:'2014',pageCount:780,language:'zh',isbn:'9787100097413',categories:['教育','哲学','文学'],desc:'《爱弥儿》是卢梭的教育小说，也是教育思想的经典之作。',domain:['成长','思维','自我','教育']},
  {title:'新爱洛伊丝',author:'让-雅克·卢梭',publisher:'上海译文出版社',publishedDate:'2011',pageCount:640,language:'zh',isbn:'9787532753495',categories:['文学','小说','书信体'],desc:'《新爱洛伊丝》是卢梭的书信体小说。',domain:['人际关系','情感','自我']},
  {title:'波斯人信札',author:'孟德斯鸠',publisher:'商务印书馆',publishedDate:'2011',pageCount:320,language:'zh',isbn:'9787100051840',categories:['文学','哲学','书信体'],desc:'《波斯人信札》是孟德斯鸠的书信体小说。',domain:['思维','认知','人际关系']},
  {title:'罗马帝国衰亡史',author:'爱德华·吉本',publisher:'商务印书馆',publishedDate:'2014',pageCount:2400,language:'zh',isbn:'9787100113906',categories:['历史','罗马','文明'],desc:'《罗马帝国衰亡史》是吉本的代表作，也是史学经典之作。',domain:['思维','认知','成长']},
  {title:'光荣与梦想',author:'威廉·曼彻斯特',publisher:'中信出版社',publishedDate:'2015',pageCount:1200,language:'zh',isbn:'9787508644885',categories:['历史','美国','传记'],desc:'《光荣与梦想》是曼彻斯特的代表作，讲述了美国的成长历程。',domain:['思维','认知','成长']},
  {title:'人类群星闪耀时',author:'茨威格',publisher:'吉林出版集团',publishedDate:'2005',pageCount:240,language:'zh',isbn:'9787807207562',categories:['历史','传记','文学'],desc:'《人类群星闪耀时》是茨威格的历史特写集，讲述了历史上的关键时刻。',domain:['思维','认知','成长']},
  {title:'昨日的世界',author:'茨威格',publisher:'广西师范大学出版社',publishedDate:'2006',pageCount:360,language:'zh',isbn:'9787563362798',categories:['历史','文学','回忆录'],desc:'《昨日的世界》是茨威格的回忆录，记录了他所经历的欧洲。',domain:['思维','自我','成长']},
  {title:'一个陌生女人的来信',author:'茨威格',publisher:'上海译文出版社',publishedDate:'2014',pageCount:220,language:'zh',isbn:'9787532765466',categories:['文学','小说','短篇'],desc:'《一个陌生女人的来信》是茨威格的短篇小说集。',domain:['情感','人际关系','自我']},
  {title:'伟大的悲剧',author:'茨威格',publisher:'江苏教育出版社',publishedDate:'2007',pageCount:240,language:'zh',isbn:'9787534365009',categories:['文学','传记','历史'],desc:'《伟大的悲剧》是茨威格的历史特写。',domain:['思维','认知','成长']},
  {title:'时间的秩序',author:'罗韦利',publisher:'湖南科学技术出版社',publishedDate:'2019',pageCount:180,language:'zh',isbn:'9787535797669',categories:['科普','物理','时间'],desc:'《时间的秩序》是罗韦利的科普著作，介绍了现代物理学对时间的认识。',domain:['思维','认知']},
  {title:'七堂极简物理课',author:'罗韦利',publisher:'湖南科学技术出版社',publishedDate:'2016',pageCount:120,language:'zh',isbn:'9787535789437',categories:['科普','物理','量子'],desc:'《七堂极简物理课》是罗韦利的科普著作，介绍了现代物理学的基本框架。',domain:['思维','认知']},
  {title:'生命是什么',author:'埃尔温·薛定谔',publisher:'商务印书馆',publishedDate:'2014',pageCount:240,language:'zh',isbn:'9787100112009',categories:['科普','物理','生物'],desc:'《生命是什么》是薛定谔的科普著作，探讨了生命的本质。',domain:['思维','认知','成长']},
  {title:'失控',author:'凯文·凯利',publisher:'新星出版社',publishedDate:'2010',pageCount:708,language:'zh',isbn:'9787513300616',categories:['科普','科技','未来'],desc:'《失控》是凯文·凯利的代表作，探讨了机器、社会、经济和生态系统的演化。',domain:['思维','认知','决策']},
  {title:'必然',author:'凯文·凯利',publisher:'新星出版社',publishedDate:'2016',pageCount:360,language:'zh',isbn:'9787513318566',categories:['科普','科技','未来'],desc:'《必然》是凯文·凯利的代表作，探讨了未来三十年的技术趋势。',domain:['思维','认知','决策']},
  {title:'硅谷钢铁侠',author:'万斯',publisher:'中信出版社',publishedDate:'2018',pageCount:320,language:'zh',isbn:'9787508686300',categories:['商业','传记','科技'],desc:'本书是埃隆·马斯克的传记。',domain:['思维','决策','自律','成长']},
  {title:'从0到1',author:'彼得·蒂尔',publisher:'中信出版社',publishedDate:'2015',pageCount:220,language:'zh',isbn:'9787508649718',categories:['商业','创业','思维'],desc:'《从0到1》是彼得·蒂尔的代表作，阐述了他的创业哲学。',domain:['思维','决策','成长']},
  {title:'精益创业',author:'埃里克·莱斯',publisher:'中信出版社',publishedDate:'2012',pageCount:360,language:'zh',isbn:'9787508642000',categories:['商业','创业','管理'],desc:'《精益创业》是埃里克·莱斯的代表作，介绍了精益创业的方法论。',domain:['思维','决策','效率','成长']},
  {title:'创新者的窘境',author:'克莱顿·克里斯坦森',publisher:'中信出版社',publishedDate:'2010',pageCount:320,language:'zh',isbn:'9787508618000',categories:['商业','管理','创新'],desc:'《创新者的窘境》是克里斯坦森的代表作，探讨了破坏性创新的本质。',domain:['思维','决策','认知']},
  {title:'商业模式新生代',author:'亚历山大·奥斯特瓦德',publisher:'机械工业出版社',publishedDate:'2011',pageCount:280,language:'zh',isbn:'9787111352299',categories:['商业','管理','创业'],desc:'《商业模式新生代》是一本关于商业模式设计的实用指南。',domain:['思维','决策','效率']},
  {title:'人类的故事',author:'房龙',publisher:'上海三联书店',publishedDate:'2014',pageCount:480,language:'zh',isbn:'9787542648540',categories:['历史','人文','科普'],desc:'《人类的故事》是房龙的代表作，讲述了人类文明的发展历程。',domain:['思维','认知','成长']},
  {title:'宽容',author:'房龙',publisher:'上海三联书店',publishedDate:'2013',pageCount:360,language:'zh',isbn:'9787542643996',categories:['历史','人文','哲学'],desc:'《宽容》是房龙的代表作，探讨了宽容的本质和历史。',domain:['思维','认知','人际关系']},
  {title:'房龙地理',author:'房龙',publisher:'上海三联书店',publishedDate:'2013',pageCount:380,language:'zh',isbn:'9787542644009',categories:['地理','人文','科普'],desc:'《房龙地理》是房龙的地理人文著作。',domain:['思维','认知']},
  {title:'明星推销员',author:'乔·吉拉德',publisher:'电子工业出版社',publishedDate:'2009',pageCount:240,language:'zh',isbn:'9787121084762',categories:['商业','营销','销售'],desc:'本书是乔·吉拉德的销售方法论。',domain:['表达','人际关系','情商']},
  {title:'销售中的心理学',author:'博恩·崔西',publisher:'电子工业出版社',publishedDate:'2008',pageCount:220,language:'zh',isbn:'9787121059808',categories:['商业','营销','心理学'],desc:'本书介绍了销售中的心理学技巧。',domain:['表达','情商','人际关系']},
  {title:'谈判力',author:'罗杰·道森',publisher:'中信出版社',publishedDate:'2014',pageCount:240,language:'zh',isbn:'9787508646601',categories:['商业','谈判','沟通'],desc:'本书介绍了谈判的技巧和策略。',domain:['表达','人际关系','情商','沟通']},
  {title:'高难度谈话',author:'道格拉斯·斯通',publisher:'新星出版社',publishedDate:'2010',pageCount:260,language:'zh',isbn:'9787513303587',categories:['沟通','人际关系','心理学'],desc:'《高难度谈话》介绍了应对困难谈话的方法和技巧。',domain:['表达','人际关系','情商','沟通']},
  {title:'关键责任',author:'帕特里克·里根',publisher:'机械工业出版社',publishedDate:'2014',pageCount:240,language:'zh',isbn:'9787111467808',categories:['沟通','人际关系','管理'],desc:'《关键责任》是《关键对话》的姊妹篇。',domain:['表达','人际关系','沟通','情商']},
  {title:'非暴力沟通实践篇',author:'马歇尔·卢森堡',publisher:'华夏出版社',publishedDate:'2014',pageCount:240,language:'zh',isbn:'9787508063025',categories:['沟通','人际关系','心理学'],desc:'本书是《非暴力沟通》的实践篇。',domain:['表达','人际关系','情商','沟通']},
  {title:'亲密关系管理',author:'陈真心',publisher:'机械工业出版社',publishedDate:'2019',pageCount:220,language:'zh',isbn:'9787111639866',categories:['心理学','人际关系','亲密关系'],desc:'本书介绍了亲密关系的管理方法。',domain:['人际关系','情商','沟通','表达']},
  {title:'爱的艺术',author:'埃里希·弗洛姆',publisher:'上海译文出版社',publishedDate:'2011',pageCount:220,language:'zh',isbn:'9787532751896',categories:['心理学','哲学','爱情'],desc:'《爱的艺术》是弗洛姆的代表作，探讨了爱的本质和艺术。',domain:['人际关系','情感','自我','成长']},
  {title:'逃避自由',author:'埃里希·弗洛姆',publisher:'上海译文出版社',publishedDate:'2015',pageCount:240,language:'zh',isbn:'9787532767149',categories:['心理学','哲学','自我'],desc:'《逃避自由》是弗洛姆的代表作，探讨了现代人的自由困境。',domain:['自由','自我','焦虑','成长']},
  {title:'自我追寻',author:'埃里希·弗洛姆',publisher:'上海译文出版社',publishedDate:'2015',pageCount:260,language:'zh',isbn:'9787532767156',categories:['心理学','哲学','自我'],desc:'本书是弗洛姆的心理学著作。',domain:['自我','成长','焦虑']},
  {title:'存在与时间',author:'马丁·海德格尔',publisher:'生活·读书·新知三联书店',publishedDate:'2015',pageCount:520,language:'zh',isbn:'9787108075080',categories:['哲学','存在主义','海德格尔'],desc:'《存在与时间》是海德格尔的代表作，也是二十世纪最具影响力的哲学著作之一。',domain:['思维','自我','成长']},
  {title:'林中路',author:'马丁·海德格尔',publisher:'生活·读书·新知三联书店',publishedDate:'2014',pageCount:320,language:'zh',isbn:'9787108049872',categories:['哲学','文学','海德格尔'],desc:'《林中路》是海德格尔的哲学论文集。',domain:['思维','自我','成长']},
  {title:'人，诗意地栖居',author:'马丁·海德格尔',publisher:'生活·读书·新知三联书店',publishedDate:'2014',pageCount:280,language:'zh',isbn:'9787108049889',categories:['哲学','文学','海德格尔'],desc:'本书是海德格尔关于艺术和诗歌的思考。',domain:['自我','成长','诗意']},
  {title:'哲学研究',author:'路德维希·维特根斯坦',publisher:'商务印书馆',publishedDate:'2013',pageCount:320,language:'zh',isbn:'9787100094528',categories:['哲学','语言','逻辑'],desc:'《哲学研究》是维特根斯坦的代表作，也是分析哲学的奠基之作。',domain:['思维','认知']},
  {title:'逻辑哲学论',author:'路德维希·维特根斯坦',publisher:'商务印书馆',publishedDate:'2013',pageCount:240,language:'zh',isbn:'9787100094511',categories:['哲学','逻辑','语言'],desc:'《逻辑哲学论》是维特根斯坦的早期代表作。',domain:['思维','认知','逻辑']},
  {title:'知觉现象学',author:'莫里斯·梅洛-庞蒂',publisher:'商务印书馆',publishedDate:'2014',pageCount:620,language:'zh',isbn:'9787100115849',categories:['哲学','现象学','梅洛-庞蒂'],desc:'《知觉现象学》是梅洛-庞蒂的代表作。',domain:['思维','自我','认知']},
  {title:'结构人类学',author:'克劳德·列维-斯特劳斯',publisher:'中国人民大学出版社',publishedDate:'2006',pageCount:480,language:'zh',isbn:'9787300045663',categories:['人类学','哲学','社会'],desc:'《结构人类学》是列维-斯特劳斯的代表作。',domain:['思维','认知']},
  {title:'野性的思维',author:'克劳德·列维-斯特劳斯',publisher:'商务印书馆',publishedDate:'2014',pageCount:320,language:'zh',isbn:'9787100106978',categories:['人类学','哲学','思维'],desc:'《野性的思维》是列维-斯特劳斯的代表作之一。',domain:['思维','认知','成长']},
  {title:'亲属制度的基本结构',author:'克劳德·列维-斯特劳斯',publisher:'商务印书馆',publishedDate:'2018',pageCount:540,language:'zh',isbn:'9787100163307',categories:['人类学','社会学','亲属'],desc:'本书是列维-斯特劳斯的人类学著作。',domain:['思维','认知','人际关系']},
  {title:'东方学',author:'爱德华·萨义德',publisher:'生活·读书·新知三联书店',publishedDate:'2007',pageCount:480,language:'zh',isbn:'9787108033046',categories:['文学批评','人类学','政治'],desc:'《东方学》是萨义德的代表作，也是后殖民批评的经典之作。',domain:['思维','认知','权力']},
  {title:'文化与帝国主义',author:'爱德华·萨义德',publisher:'生活·读书·新知三联书店',publishedDate:'2004',pageCount:420,language:'zh',isbn:'9787108025874',categories:['文学批评','人类学','政治'],desc:'本书是萨义德的文化研究著作。',domain:['思维','认知','权力']},
  {title:'知识分子论',author:'爱德华·萨义德',publisher:'生活·读书·新知三联书店',publishedDate:'2002',pageCount:280,language:'zh',isbn:'9787108022538',categories:['文学批评','文化','社会'],desc:'本书是萨义德的知识分子论。',domain:['思维','认知','自我']},
  {title:'论语言的起源',author:'卢梭/赫尔德',publisher:'商务印书馆',publishedDate:'2014',pageCount:280,language:'zh',isbn:'9787100114033',categories:['语言学','哲学','起源'],desc:'本书收录了卢梭和赫尔德关于语言起源的论著。',domain:['思维','认知','语言']},
  {title:'普通语言学教程',author:'费尔迪南·德·索绪尔',publisher:'商务印书馆',publishedDate:'1980',pageCount:340,language:'zh',isbn:'9787100013215',categories:['语言学','哲学','符号学'],desc:'《普通语言学教程》是索绪尔的代表作，也是现代语言学的奠基之作。',domain:['思维','认知','语言']},
  {title:'符号学原理',author:'罗兰·巴特',publisher:'生活·读书·新知三联书店',publishedDate:'1999',pageCount:280,language:'zh',isbn:'9787108017619',categories:['符号学','文学批评','文化'],desc:'《符号学原理》是巴特的代表作之一。',domain:['思维','认知','文化']},
  {title:'恋人絮语',author:'罗兰·巴特',publisher:'上海人民出版社',publishedDate:'2009',pageCount:320,language:'zh',isbn:'9787208053092',categories:['文学','哲学','爱情'],desc:'《恋人絮语》是巴特的代表作，以碎片的形式探讨了爱情。',domain:['爱情','人际关系','自我']},
  {title:'写作的零度',author:'罗兰·巴特',publisher:'中国人民大学出版社',publishedDate:'2008',pageCount:240,language:'zh',isbn:'9787300070633',categories:['文学批评','符号学','文化'],desc:'《写作的零度》是巴特的早期代表作。',domain:['思维','认知','写作']},
  {title:'沉默的大多数',author:'王小波',publisher:'北京十月文艺出版社',publishedDate:'2012',pageCount:280,language:'zh',isbn:'9787530211870',categories:['文学','散文','随笔'],desc:'《沉默的大多数》是王小波的杂文精选集。',domain:['思维','自我','成长','表达']},
  {title:'我的精神家园',author:'王小波',publisher:'北京十月文艺出版社',publishedDate:'2012',pageCount:260,language:'zh',isbn:'9787530211887',categories:['文学','散文','随笔'],desc:'《我的精神家园》是王小波的杂文精选集。',domain:['思维','自我','成长']},
  {title:'黄金时代',author:'王小波',publisher:'北京十月文艺出版社',publishedDate:'2012',pageCount:320,language:'zh',isbn:'9787530211894',categories:['文学','小说','时代'],desc:'《黄金时代》是王小波的长篇小说。',domain:['思维','自我','成长']},
  {title:'三十而立',author:'王小波',publisher:'北京十月文艺出版社',publishedDate:'2012',pageCount:240,language:'zh',isbn:'9787530211900',categories:['文学','小说'],desc:'《三十而立》是王小波的短篇小说。',domain:['自我','成长','思维']},
  {title:'寻找无双',author:'王小波',publisher:'北京十月文艺出版社',publishedDate:'2012',pageCount:220,language:'zh',isbn:'9787530211917',categories:['文学','小说'],desc:'《寻找无双》是王小波的小说作品。',domain:['思维','自我','成长']},
  {title:'革命时期的爱情',author:'王小波',publisher:'北京十月文艺出版社',publishedDate:'2012',pageCount:260,language:'zh',isbn:'9787530211924',categories:['文学','小说'],desc:'《革命时期的爱情》是王小波的长篇小说。',domain:['思维','自我','成长']},
  {title:'万寿寺',author:'王小波',publisher:'北京十月文艺出版社',publishedDate:'2012',pageCount:280,language:'zh',isbn:'9787530211931',categories:['文学','小说'],desc:'《万寿寺》是王小波的长篇小说。',domain:['思维','自我','成长']},
  {title:'红拂夜奔',author:'王小波',publisher:'北京十月文艺出版社',publishedDate:'2012',pageCount:260,language:'zh',isbn:'9787530211948',categories:['文学','小说'],desc:'《红拂夜奔》是王小波的长篇小说。',domain:['思维','自我','成长']},
  {title:'夜行记',author:'王小波',publisher:'北京十月文艺出版社',publishedDate:'2012',pageCount:220,language:'zh',isbn:'9787530211955',categories:['文学','小说'],desc:'《夜行记》是王小波的短篇小说集。',domain:['思维','自我','成长']},
  {title:'绿毛水怪',author:'王小波',publisher:'北京十月文艺出版社',publishedDate:'2012',pageCount:200,language:'zh',isbn:'9787530211962',categories:['文学','小说','短篇'],desc:'《绿毛水怪》是王小波的短篇小说。',domain:['思维','自我','成长']},
  {title:'围城',author:'钱钟书',publisher:'人民文学出版社',publishedDate:'1991',pageCount:359,language:'zh',isbn:'9787020024759',categories:['文学','小说','讽刺'],desc:'《围城》是钱钟书的代表作，被誉为"新儒林外史"。',domain:['人际关系','自我','成长','表达']},
  {title:'管锥编',author:'钱钟书',publisher:'中华书局',publishedDate:'1979',pageCount:3200,language:'zh',isbn:'9787101007200',categories:['文学','国学','笔记'],desc:'《管锥编》是钱钟书的学术巨著。',domain:['思维','认知']},
  {title:'谈艺录',author:'钱钟书',publisher:'中华书局',publishedDate:'1984',pageCount:480,language:'zh',isbn:'9787101012202',categories:['文学','国学','评论'],desc:'《谈艺录》是钱钟书的文学评论集。',domain:['思维','认知','写作']},
  {title:'人间词话',author:'王国维',publisher:'人民文学出版社',publishedDate:'1960',pageCount:160,language:'zh',isbn:'9787020026548',categories:['文学','国学','词学'],desc:'《人间词话》是王国维的代表作，也是中国近代最重要的文学批评著作。',domain:['思维','认知','写作']},
  {title:'红楼梦',author:'曹雪芹/高鹗',publisher:'人民文学出版社',publishedDate:'1996',pageCount:1606,language:'zh',isbn:'9787020002207',categories:['文学','古典','小说'],desc:'《红楼梦》是中国古典四大名著之首，讲述了贾、史、王、薛四大家族的兴衰。',domain:['人际关系','成长','自我','表达']},
  {title:'西游记',author:'吴承恩',publisher:'人民文学出版社',publishedDate:'2005',pageCount:986,language:'zh',isbn:'9787020024759',categories:['文学','古典','小说'],desc:'《西游记》是中国古典四大名著之一，讲述了唐僧师徒西天取经的故事。',domain:['思维','自我','成长']},
  {title:'三国演义',author:'罗贯中',publisher:'人民文学出版社',publishedDate:'2002',pageCount:1200,language:'zh',isbn:'9787020012009',categories:['文学','古典','小说'],desc:'《三国演义》是中国古典四大名著之一，讲述了三国时期的历史故事。',domain:['思维','决策','成长','认知']},
  {title:'水浒传',author:'施耐庵',publisher:'人民文学出版社',publishedDate:'2005',pageCount:950,language:'zh',isbn:'9787020024766',categories:['文学','古典','小说'],desc:'《水浒传》是中国古典四大名著之一，讲述了梁山好汉的故事。',domain:['思维','自我','成长']},
  {title:'聊斋志异',author:'蒲松龄',publisher:'人民文学出版社',publishedDate:'2005',pageCount:480,language:'zh',isbn:'9787020024773',categories:['文学','古典','志怪'],desc:'《聊斋志异》是蒲松龄的代表作，讲述了狐鬼花妖的故事。',domain:['思维','自我','成长']},
  {title:'牡丹亭',author:'汤显祖',publisher:'人民文学出版社',publishedDate:'2005',pageCount:320,language:'zh',isbn:'9787020002214',categories:['文学','古典','戏曲'],desc:'《牡丹亭》是汤显祖的代表作，也是中国古典戏曲的经典之作。',domain:['情感','人际关系','自我']},
  {title:'西厢记',author:'王实甫',publisher:'人民文学出版社',publishedDate:'2005',pageCount:280,language:'zh',isbn:'9787020002221',categories:['文学','古典','戏曲'],desc:'《西厢记》是王实甫的代表作，也是中国古典戏曲的经典之作。',domain:['情感','人际关系','自我']},
  {title:'浮生六记',author:'沈复',publisher:'人民文学出版社',publishedDate:'2005',pageCount:240,language:'zh',isbn:'9787020002238',categories:['文学','古典','自传'],desc:'《浮生六记》是沈复的自传体作品。',domain:['情感','人际关系','自我','成长']},
  {title:'古文观止',author:'吴楚材/吴调侯',publisher:'人民文学出版社',publishedDate:'2005',pageCount:560,language:'zh',isbn:'9787020002245',categories:['文学','古典','散文'],desc:'《古文观止》是一部历代散文选集。',domain:['思维','认知','写作']},
  {title:'唐诗三百首',author:'蘅塘退士',publisher:'人民文学出版社',publishedDate:'2005',pageCount:360,language:'zh',isbn:'9787020002252',categories:['文学','古典','诗歌'],desc:'《唐诗三百首》是一部唐诗选集。',domain:['思维','写作','表达']},
  {title:'诗经',author:'佚名',publisher:'人民文学出版社',publishedDate:'2005',pageCount:480,language:'zh',isbn:'9787020002269',categories:['文学','古典','诗歌'],desc:'《诗经》是中国最早的诗歌总集。',domain:['思维','表达','情感']},
  {title:'论语',author:'孔子',publisher:'人民文学出版社',publishedDate:'2005',pageCount:280,language:'zh',isbn:'9787020002276',categories:['哲学','古典','儒家'],desc:'《论语》是孔子的弟子及其再传弟子编撰的儒家经典。',domain:['思维','自我','成长','人际关系']},
  {title:'孟子',author:'孟子',publisher:'人民文学出版社',publishedDate:'2005',pageCount:320,language:'zh',isbn:'9787020002283',categories:['哲学','古典','儒家'],desc:'《孟子》是儒家经典之一。',domain:['思维','自我','成长']},
  {title:'大学',author:'曾子',publisher:'人民文学出版社',publishedDate:'2005',pageCount:160,language:'zh',isbn:'9787020002290',categories:['哲学','古典','儒家'],desc:'《大学》是儒家经典之一。',domain:['思维','自我','成长']},
  {title:'中庸',author:'子思',publisher:'人民文学出版社',publishedDate:'2005',pageCount:160,language:'zh',isbn:'9787020002306',categories:['哲学','古典','儒家'],desc:'《中庸》是儒家经典之一。',domain:['思维','自我','成长']},
  {title:'道德经',author:'老子',publisher:'人民文学出版社',publishedDate:'2005',pageCount:200,language:'zh',isbn:'9787020002313',categories:['哲学','古典','道家'],desc:'《道德经》是老子的代表作，也是道家学派的经典之作。',domain:['思维','自我','成长','认知']},
  {title:'庄子',author:'庄周',publisher:'人民文学出版社',publishedDate:'2005',pageCount:520,language:'zh',isbn:'9787020002320',categories:['哲学','古典','道家'],desc:'《庄子》是庄子的代表作，也是道家学派的经典之作。',domain:['思维','自我','成长','自由']},
  {title:'墨子',author:'墨翟',publisher:'人民文学出版社',publishedDate:'2005',pageCount:360,language:'zh',isbn:'9787020002337',categories:['哲学','古典','墨家'],desc:'《墨子》是墨子的代表作，也是墨家学派的经典之作。',domain:['思维','自我','成长','认知']},
  {title:'韩非子',author:'韩非',publisher:'人民文学出版社',publishedDate:'2005',pageCount:580,language:'zh',isbn:'9787020002344',categories:['哲学','古典','法家'],desc:'《韩非子》是韩非子的代表作，也是法家学派的经典之作。',domain:['思维','自我','成长','认知']},
  {title:'史记',author:'司马迁',publisher:'中华书局',publishedDate:'2014',pageCount:3000,language:'zh',isbn:'9787101011502',categories:['历史','古典','纪传体'],desc:'《史记》是司马迁的代表作，也是中国第一部纪传体通史。',domain:['思维','认知','成长']},
  {title:'资治通鉴',author:'司马光',publisher:'中华书局',publishedDate:'2011',pageCount:6000,language:'zh',isbn:'9787101053907',categories:['历史','古典','编年体'],desc:'《资治通鉴》是司马光主编的编年体通史。',domain:['思维','认知','决策']},
  {title:'明朝那些事儿',author:'当年明月',publisher:'浙江人民出版社',publishedDate:'2009',pageCount:2200,language:'zh',isbn:'9787213202841',categories:['历史','通俗','明朝'],desc:'《明朝那些事儿》是当年明月的历史通俗读物。',domain:['思维','认知','成长']},
  {title:'人类简史',author:'尤瓦尔·赫拉利',publisher:'中信出版社',publishedDate:'2014',pageCount:440,language:'zh',isbn:'9787508644653',categories:['历史','人类学','科普'],desc:'《人类简史》从认知革命、农业革命到科学革命，讲述了人类从石器时代到21世纪的演化历程。',domain:['思维','认知','成长']},
  {title:'未来简史',author:'尤瓦尔·赫拉利',publisher:'中信出版社',publishedDate:'2017',pageCount:420,language:'zh',isbn:'9787508681435',categories:['历史','未来学','科普'],desc:'《未来简史》是《人类简史》的姊妹篇，探讨了智人未来的发展方向。',domain:['思维','认知']},
  {title:'今日简史',author:'尤瓦尔·赫拉利',publisher:'中信出版社',publishedDate:'2019',pageCount:320,language:'zh',isbn:'9787521718238',categories:['历史','社会','时事'],desc:'《今日简史》聚焦当下，分析了当今世界面临的十大挑战。',domain:['思维','认知','成长']}
];

function searchLocalCatalog(query){
  if(!query || !query.trim()) return [];
  var q = query.trim().toLowerCase();
  var tokens = q.split(/\s+/);
  var results = [];
  for(var i = 0; i < LOCAL_BOOK_CATALOG.length; i++){
    var b = LOCAL_BOOK_CATALOG[i];
    var haystack = (b.title + ' ' + (b.author || '') + ' ' + (b.publisher || '')).toLowerCase();
    var score = 0;
    var matched = false;
    if(haystack.indexOf(q) >= 0){
      score += 100; matched = true;
    }
    for(var t = 0; t < tokens.length; t++){
      if(tokens[t] && haystack.indexOf(tokens[t]) >= 0){
        score += 20;
      }
    }
    if(b.domain){
      for(var d = 0; d < b.domain.length; d++){
        if(q.indexOf(b.domain[d]) >= 0 || b.domain[d].indexOf(q) >= 0){
          score += 5; matched = true;
        }
      }
    }
    if(matched || score > 0){
      b._score = score;
      results.push(b);
    }
  }
  results.sort(function(a,b){ return (b._score || 0) - (a._score || 0); });
  return results.slice(0, 5);
}

function lookupLocalCatalog(title, author){
  var results = searchLocalCatalog((title || '') + ' ' + (author || ''));
  if(results.length === 0 && title){
    results = searchLocalCatalog(title);
  }
  if(results.length === 0) return null;
  var best = results[0];
  return {
    title: best.title,
    authors: best.author || '',
    desc: (best.desc || '').substring(0, 500),
    categories: best.categories || [],
    pageCount: best.pageCount || 0,
    publishedDate: best.publishedDate || '',
    publisher: best.publisher || '',
    language: best.language || '',
    isbn: best.isbn || '',
    cover: '',
    _local: true,
    _preDomains: best.domain || []
  };
}


